name: Build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 17
          cache: 'gradle'
      - name: Configure Git
        run: git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
      - name: Build
        if: "!contains(github.event.head_commit.message, '--skip') && !contains(github.event.head_commit.commit.message, '--skip')"
        run: ./gradlew build
      - name: Publish
        if: "!contains(github.event.head_commit.message, '--skip') && !contains(github.event.head_commit.commit.message, '--skip')"
        run: ./gradlew publishAllPublicationsToSonatypeRepository --info
      - name: Rebuild on Failure
        if: ${{ failure() }}
        run: |
          ./gradlew build
          ./gradlew publishAllPublicationsToSonatypeRepository --info